# File name: floatlayout.kv
<Button>:
	color: .8, .9, 0, 1
	font_size: 32
	size_hint: .4, .3

<FloatLayout>:
	Button:
		text: 'Hello'
		pos_hint: {'x':0, 'top':1}
	Button:
		text: 'World'
		pos_hint: {'right':1, 'y':0}
	
	Button:
		text: 'John'
		pos_hint: {'x':0, 'y':0}
	Button:
		text: 'Liceli'
		pos_hint: {'right':1, 'top':1}
	Button:
		text: 'Lynn'
		pos_hint: {'center_x':.5, 'center_y':.5}