# File name: widgets2.py
<MyButton@Button>:
	color: .8, .9, 0, 1
	font_size: 32
	size: 100, 50
<MyWidget>:
	MyButton:
		text: 'Hello'
		pos: root.x, root.top - self.height # 0, 1
	MyButton:
		text: 'Kivy'
		pos: root.right - self.width, root.y # 1, 0
	MyButton:
		text: 'John'
		pos: root.x, root.y # 0, 0
	MyButton:
		text: 'Liceli'
		pos: root.right - self.width, root.top - self.height # 1, 1